"""Synchronized rollout and replay buffers for raw PyTorch joint MARL training."""

from __future__ import annotations

from collections.abc import Mapping, MutableMapping
from dataclasses import dataclass, field
import math
import time
from typing import Any, Final, Iterator

import torch
from torch import Tensor

from src.act.action_projector import CONTINUOUS_ACTION_DIM
from src.act.discrete_action_mapper import DISCRETE_ACTION_COUNT
from src.act.observation_builder import OBSERVATION_DIM


DQN_REPLAY_STATE_VERSION: Final[str] = "dqn_replay_buffer_v1"


@dataclass(frozen=True, slots=True)
class JointRewardBlendConfig:
    """Role-specific reward blend contract for synchronized PPO/DQN learning."""

    ppo_global_weight: float = 0.35
    ppo_local_weight: float = 0.65
    dqn_local_weight: float = 0.90
    dqn_global_weight: float = 0.10
    dqn_local_health_offset: float = 0.10
    dqn_local_health_scale: float = 0.25

    def __post_init__(self) -> None:
        for name, value in {
            "ppo_global_weight": self.ppo_global_weight,
            "ppo_local_weight": self.ppo_local_weight,
            "dqn_local_weight": self.dqn_local_weight,
            "dqn_global_weight": self.dqn_global_weight,
            "dqn_local_health_offset": self.dqn_local_health_offset,
            "dqn_local_health_scale": self.dqn_local_health_scale,
        }.items():
            _validate_finite_float(name, value)
            if name.endswith("_weight") and value < 0.0:
                raise ValueError(f"{name} must not be negative.")
        if self.ppo_global_weight + self.ppo_local_weight <= 0.0:
            raise ValueError("at least one PPO reward weight must be positive.")
        if self.dqn_local_weight + self.dqn_global_weight <= 0.0:
            raise ValueError("at least one DQN reward weight must be positive.")
        if self.dqn_local_health_scale <= 0.0:
            raise ValueError("dqn_local_health_scale must be positive.")


@dataclass(frozen=True, slots=True)
class JointTransition:
    """Atomic transition generated by one joint PPO+DQN environment step."""

    observation: Tensor
    ppo_action: Tensor
    ppo_log_prob: Tensor
    ppo_value: Tensor
    dqn_action: Tensor
    reward_total: float
    reward_global: float
    reward_ppo_local: float
    reward_dqn_local: float
    reward_ppo_train: float
    reward_dqn_train: float
    next_observation: Tensor
    terminated: bool
    truncated: bool
    projected: bool
    blocked: bool
    info: dict[str, Any] = field(default_factory=dict)
    joint_action_id: str = ""
    episode_id: str = ""
    step_id: int = 0

    @classmethod
    def from_reward_components(
        cls,
        *,
        observation: Tensor,
        ppo_action: Tensor,
        ppo_log_prob: Tensor,
        ppo_value: Tensor,
        dqn_action: Tensor,
        reward_total: float,
        reward_global: float,
        reward_ppo_local: float,
        reward_dqn_local: float,
        reward_blend: JointRewardBlendConfig | None = None,
        next_observation: Tensor,
        terminated: bool,
        truncated: bool,
        projected: bool,
        blocked: bool,
        info: dict[str, Any] | None = None,
        joint_action_id: str = "",
        episode_id: str = "",
        step_id: int = 0,
    ) -> JointTransition:
        for name, value in {
            "reward_total": reward_total,
            "reward_global": reward_global,
            "reward_ppo_local": reward_ppo_local,
            "reward_dqn_local": reward_dqn_local,
        }.items():
            _validate_finite_float(name, value)
        blend = reward_blend or JointRewardBlendConfig()
        reward_ppo_train = ppo_training_reward(
            reward_global=reward_global,
            reward_ppo_local=reward_ppo_local,
            reward_blend=blend,
        )
        reward_dqn_train = dqn_training_reward(
            reward_global=reward_global,
            reward_dqn_local=reward_dqn_local,
            reward_blend=blend,
        )
        return cls(
            observation=observation,
            ppo_action=ppo_action,
            ppo_log_prob=ppo_log_prob,
            ppo_value=ppo_value,
            dqn_action=dqn_action,
            reward_total=reward_total,
            reward_global=reward_global,
            reward_ppo_local=reward_ppo_local,
            reward_dqn_local=reward_dqn_local,
            reward_ppo_train=float(reward_ppo_train),
            reward_dqn_train=float(reward_dqn_train),
            next_observation=next_observation,
            terminated=terminated,
            truncated=truncated,
            projected=projected,
            blocked=blocked,
            info=info or {},
            joint_action_id=joint_action_id,
            episode_id=episode_id,
            step_id=step_id,
        )

    def __post_init__(self) -> None:
        for name, value in {
            "reward_total": self.reward_total,
            "reward_global": self.reward_global,
            "reward_ppo_local": self.reward_ppo_local,
            "reward_dqn_local": self.reward_dqn_local,
            "reward_ppo_train": self.reward_ppo_train,
            "reward_dqn_train": self.reward_dqn_train,
        }.items():
            _validate_finite_float(name, value)

    @property
    def done(self) -> bool:
        return self.terminated or self.truncated

    @property
    def bootstrap_done(self) -> bool:
        return self.terminated


@dataclass(frozen=True, slots=True)
class PPORolloutBatch:
    observations: Tensor
    actions: Tensor
    old_log_probs: Tensor
    old_values: Tensor
    returns: Tensor
    advantages: Tensor


@dataclass(frozen=True, slots=True)
class DQNReplayBatch:
    observations: Tensor
    actions: Tensor
    rewards: Tensor
    next_observations: Tensor
    dones: Tensor


@dataclass(frozen=True, slots=True)
class DQNReplayItem:
    """Compact replay payload; avoids retaining trace/info objects for long runs."""

    observation: Tensor
    action: Tensor
    reward: float
    next_observation: Tensor
    done: bool


class PPORolloutBuffer:
    """On-policy buffer storing exactly one synchronized PPO rollout."""

    def __init__(
        self,
        *,
        rollout_steps: int,
        device: torch.device | str,
        gamma: float = 0.99,
        gae_lambda: float = 0.95,
        reward_blend: JointRewardBlendConfig | None = None,
        observation_dim: int = OBSERVATION_DIM,
        action_dim: int = CONTINUOUS_ACTION_DIM,
    ) -> None:
        if rollout_steps <= 0:
            raise ValueError("rollout_steps must be positive.")
        _validate_discount("gamma", gamma)
        _validate_discount("gae_lambda", gae_lambda)

        self.rollout_steps = rollout_steps
        self.device = torch.device(device)
        self.gamma = float(gamma)
        self.gae_lambda = float(gae_lambda)
        self.reward_blend = reward_blend or JointRewardBlendConfig()
        self.observation_dim = observation_dim
        self.action_dim = action_dim
        self._transitions: list[JointTransition] = []
        self._batch: PPORolloutBatch | None = None

    def __len__(self) -> int:
        return len(self._transitions)

    @property
    def is_full(self) -> bool:
        return len(self._transitions) >= self.rollout_steps

    def add(self, transition: JointTransition) -> None:
        if self.is_full:
            raise RuntimeError("PPO rollout buffer is full; compute/update then reset before adding more transitions.")
        self._validate_transition(transition)
        self._transitions.append(transition)
        self._batch = None

    def reset(self) -> None:
        self._transitions.clear()
        self._batch = None

    def compute_returns_and_advantages(
        self,
        *,
        last_value: Tensor | float = 0.0,
        last_terminated: bool | None = None,
    ) -> PPORolloutBatch:
        if not self._transitions:
            raise RuntimeError("cannot compute PPO returns from an empty rollout buffer.")

        observations = torch.stack(
            [_tensor_1d(t.observation, expected_dim=self.observation_dim, device=self.device) for t in self._transitions]
        )
        actions = torch.stack(
            [_tensor_1d(t.ppo_action, expected_dim=self.action_dim, device=self.device) for t in self._transitions]
        )
        old_log_probs = torch.stack([_scalar_tensor(t.ppo_log_prob, device=self.device) for t in self._transitions])
        old_values = torch.stack([_scalar_tensor(t.ppo_value, device=self.device) for t in self._transitions])
        rewards = torch.tensor(
            [
                _weighted_reward(
                    global_reward=t.reward_global,
                    local_reward=t.reward_ppo_local,
                    explicit_reward=t.reward_ppo_train,
                    expected_reward=ppo_training_reward(
                        reward_global=t.reward_global,
                        reward_ppo_local=t.reward_ppo_local,
                        reward_blend=self.reward_blend,
                    ),
                )
                for t in self._transitions
            ],
            dtype=torch.float32,
            device=self.device,
        )
        bootstrap_dones = torch.tensor([t.bootstrap_done for t in self._transitions], dtype=torch.float32, device=self.device)
        last_value_tensor = _scalar_tensor(last_value, device=self.device)
        final_terminated = self._transitions[-1].terminated if last_terminated is None else last_terminated
        if final_terminated:
            last_value_tensor = torch.zeros((), dtype=torch.float32, device=self.device)

        advantages = torch.zeros(len(self._transitions), dtype=torch.float32, device=self.device)
        last_gae = torch.zeros((), dtype=torch.float32, device=self.device)
        for step in range(len(self._transitions) - 1, -1, -1):
            if step == len(self._transitions) - 1:
                next_non_terminal = (
                    torch.zeros((), dtype=torch.float32, device=self.device)
                    if final_terminated
                    else 1.0 - bootstrap_dones[step]
                )
                next_value = last_value_tensor
            else:
                next_non_terminal = 1.0 - bootstrap_dones[step]
                next_value = old_values[step + 1]

            delta = rewards[step] + (self.gamma * next_value * next_non_terminal) - old_values[step]
            last_gae = delta + (self.gamma * self.gae_lambda * next_non_terminal * last_gae)
            advantages[step] = last_gae

        returns = advantages + old_values
        self._batch = PPORolloutBatch(
            observations=observations,
            actions=actions,
            old_log_probs=old_log_probs,
            old_values=old_values,
            returns=returns,
            advantages=advantages,
        )
        return self._batch

    def iter_minibatches(
        self,
        *,
        minibatch_size: int,
        shuffle: bool = True,
        normalize_advantages: bool = True,
    ) -> Iterator[PPORolloutBatch]:
        if minibatch_size <= 0:
            raise ValueError("minibatch_size must be positive.")
        if self._batch is None:
            raise RuntimeError("compute_returns_and_advantages must be called before iterating PPO minibatches.")

        batch = self._batch
        size = batch.observations.shape[0]
        indices = torch.randperm(size, device=self.device) if shuffle else torch.arange(size, device=self.device)
        advantages = batch.advantages
        if normalize_advantages and advantages.numel() > 1:
            advantages = (advantages - advantages.mean()) / (advantages.std(unbiased=False) + 1e-8)

        for start in range(0, size, minibatch_size):
            idx = indices[start : start + minibatch_size]
            yield PPORolloutBatch(
                observations=batch.observations[idx],
                actions=batch.actions[idx],
                old_log_probs=batch.old_log_probs[idx],
                old_values=batch.old_values[idx],
                returns=batch.returns[idx],
                advantages=advantages[idx],
            )

    def _validate_transition(self, transition: JointTransition) -> None:
        _tensor_1d(transition.observation, expected_dim=self.observation_dim, device=self.device)
        _tensor_1d(transition.ppo_action, expected_dim=self.action_dim, device=self.device)
        _scalar_tensor(transition.ppo_log_prob, device=self.device)
        _scalar_tensor(transition.ppo_value, device=self.device)


class DQNReplayBuffer:
    """Ring-buffer replay store for DQN updates using joint transitions."""

    def __init__(
        self,
        *,
        capacity: int,
        learning_starts: int,
        device: torch.device | str,
        reward_blend: JointRewardBlendConfig | None = None,
        observation_dim: int = OBSERVATION_DIM,
        action_count: int = DISCRETE_ACTION_COUNT,
    ) -> None:
        if capacity <= 0:
            raise ValueError("capacity must be positive.")
        if learning_starts < 0:
            raise ValueError("learning_starts must not be negative.")
        if observation_dim <= 0:
            raise ValueError("observation_dim must be positive.")
        if action_count <= 0:
            raise ValueError("action_count must be positive.")

        self.capacity = capacity
        self.learning_starts = learning_starts
        self.device = torch.device(device)
        self.reward_blend = reward_blend or JointRewardBlendConfig()
        self.observation_dim = observation_dim
        self.action_count = action_count
        storage_device = torch.device("cpu")
        self._observations = torch.empty((capacity, observation_dim), dtype=torch.float32, device=storage_device)
        self._actions = torch.empty((capacity,), dtype=torch.long, device=storage_device)
        self._rewards = torch.empty((capacity,), dtype=torch.float32, device=storage_device)
        self._next_observations = torch.empty((capacity, observation_dim), dtype=torch.float32, device=storage_device)
        self._dones = torch.empty((capacity,), dtype=torch.bool, device=storage_device)
        self._position = 0
        self._size = 0
        self._total_added = 0

    def __len__(self) -> int:
        return self._size

    @property
    def total_added(self) -> int:
        return self._total_added

    @property
    def can_sample(self) -> bool:
        return self._total_added >= self.learning_starts and self._size > 0

    def state_dict(self) -> dict[str, Any]:
        """Return a compact CPU snapshot of the valid ring-buffer storage."""

        return {
            "version": DQN_REPLAY_STATE_VERSION,
            "capacity": self.capacity,
            "learning_starts": self.learning_starts,
            "observation_dim": self.observation_dim,
            "action_count": self.action_count,
            "position": self._position,
            "size": self._size,
            "total_added": self._total_added,
            "observations": self._observations[: self._size].clone(),
            "actions": self._actions[: self._size].clone(),
            "rewards": self._rewards[: self._size].clone(),
            "next_observations": self._next_observations[: self._size].clone(),
            "dones": self._dones[: self._size].clone(),
        }

    def load_state_dict(self, state: Mapping[str, Any]) -> None:
        """Restore a replay snapshot into this configured replay buffer."""

        if not isinstance(state, Mapping):
            raise TypeError("DQN replay state must be a mapping.")
        version = state.get("version")
        if version != DQN_REPLAY_STATE_VERSION:
            raise ValueError(f"unsupported DQN replay state version: {version!r}.")
        capacity = int(state.get("capacity", -1))
        learning_starts = int(state.get("learning_starts", -1))
        observation_dim = int(state.get("observation_dim", -1))
        action_count = int(state.get("action_count", -1))
        if capacity != self.capacity:
            raise ValueError(f"DQN replay capacity mismatch: checkpoint={capacity}, buffer={self.capacity}.")
        if learning_starts != self.learning_starts:
            raise ValueError(
                f"DQN replay learning_starts mismatch: checkpoint={learning_starts}, buffer={self.learning_starts}."
            )
        if observation_dim != self.observation_dim:
            raise ValueError(
                f"DQN replay observation_dim mismatch: checkpoint={observation_dim}, buffer={self.observation_dim}."
            )
        if action_count != self.action_count:
            raise ValueError(f"DQN replay action_count mismatch: checkpoint={action_count}, buffer={self.action_count}.")

        size = int(state.get("size", -1))
        position = int(state.get("position", -1))
        total_added = int(state.get("total_added", -1))
        if size < 0 or size > self.capacity:
            raise ValueError(f"DQN replay size must be within [0, {self.capacity}], got {size}.")
        if position < 0 or position >= self.capacity:
            raise ValueError(f"DQN replay position must be within [0, {self.capacity - 1}], got {position}.")
        if total_added < size:
            raise ValueError(f"DQN replay total_added {total_added} must be >= size {size}.")

        observations = _state_tensor(state, "observations", dtype=torch.float32)
        actions = _state_tensor(state, "actions", dtype=torch.long)
        rewards = _state_tensor(state, "rewards", dtype=torch.float32)
        next_observations = _state_tensor(state, "next_observations", dtype=torch.float32)
        dones = _state_tensor(state, "dones", dtype=torch.bool)
        expected_observation_shape = (size, self.observation_dim)
        if tuple(observations.shape) != expected_observation_shape:
            raise ValueError(
                f"DQN replay observations shape mismatch: expected {expected_observation_shape}, "
                f"got {tuple(observations.shape)}."
            )
        if tuple(next_observations.shape) != expected_observation_shape:
            raise ValueError(
                f"DQN replay next_observations shape mismatch: expected {expected_observation_shape}, "
                f"got {tuple(next_observations.shape)}."
            )
        for name, tensor in {"actions": actions, "rewards": rewards, "dones": dones}.items():
            if tuple(tensor.shape) != (size,):
                raise ValueError(f"DQN replay {name} shape mismatch: expected {(size,)}, got {tuple(tensor.shape)}.")
        _validate_finite_tensor("dqn_replay_observations", observations)
        _validate_finite_tensor("dqn_replay_rewards", rewards)
        _validate_finite_tensor("dqn_replay_next_observations", next_observations)
        if actions.numel() > 0:
            min_action = int(actions.min().item())
            max_action = int(actions.max().item())
            if min_action < 0 or max_action >= self.action_count:
                raise ValueError(
                    f"DQN replay actions must be within [0, {self.action_count - 1}], got [{min_action}, {max_action}]."
                )

        self._observations.zero_()
        self._actions.zero_()
        self._rewards.zero_()
        self._next_observations.zero_()
        self._dones.zero_()
        if size > 0:
            self._observations[:size].copy_(observations.to(device=torch.device("cpu"), dtype=torch.float32))
            self._actions[:size].copy_(actions.to(device=torch.device("cpu"), dtype=torch.long))
            self._rewards[:size].copy_(rewards.to(device=torch.device("cpu"), dtype=torch.float32))
            self._next_observations[:size].copy_(
                next_observations.to(device=torch.device("cpu"), dtype=torch.float32)
            )
            self._dones[:size].copy_(dones.to(device=torch.device("cpu"), dtype=torch.bool))
        self._position = position
        self._size = size
        self._total_added = total_added

    def state_summary(self) -> dict[str, int | bool]:
        return {
            "capacity": self.capacity,
            "learning_starts": self.learning_starts,
            "position": self._position,
            "size": self._size,
            "total_added": self._total_added,
            "can_sample": self.can_sample,
        }

    def add(self, transition: JointTransition) -> None:
        item = self._compact_transition(transition)
        self._observations[self._position].copy_(item.observation)
        self._actions[self._position] = int(item.action.item())
        self._rewards[self._position] = float(item.reward)
        self._next_observations[self._position].copy_(item.next_observation)
        self._dones[self._position] = bool(item.done)
        self._position = (self._position + 1) % self.capacity
        self._size = min(self._size + 1, self.capacity)
        self._total_added += 1

    def sample(
        self,
        batch_size: int,
        *,
        timing: MutableMapping[str, float] | None = None,
        validate_tensors: bool = False,
    ) -> DQNReplayBatch:
        if batch_size <= 0:
            raise ValueError("batch_size must be positive.")
        if not self.can_sample:
            raise RuntimeError(
                f"DQN replay buffer cannot sample before learning_starts={self.learning_starts}; "
                f"total_added={self._total_added}."
            )
        if batch_size > self._size:
            raise ValueError(f"batch_size {batch_size} exceeds replay size {self._size}.")

        sample_started = time.perf_counter()
        indices = torch.randint(low=0, high=self._size, size=(batch_size,), device=torch.device("cpu"))
        _add_timing(timing, "dqn_replay_sample_seconds_window", time.perf_counter() - sample_started)
        return self._sample_at_indices(indices, timing=timing, validate_tensors=validate_tensors)

    def _sample_at_indices(
        self,
        indices: Tensor,
        *,
        timing: MutableMapping[str, float] | None = None,
        validate_tensors: bool = False,
    ) -> DQNReplayBatch:
        sample_started = time.perf_counter()
        if self._size <= 0:
            raise RuntimeError("cannot sample from an empty DQN replay buffer.")
        if indices.ndim != 1:
            raise ValueError(f"expected 1D replay indices, got shape {tuple(indices.shape)}.")
        indices_cpu = indices.detach().to(device=torch.device("cpu"), dtype=torch.long)
        if indices_cpu.numel() <= 0:
            raise ValueError("replay indices must not be empty.")
        min_index = int(indices_cpu.min().item())
        max_index = int(indices_cpu.max().item())
        if min_index < 0 or max_index >= self._size:
            raise ValueError(f"replay indices must be within [0, {self._size - 1}], got [{min_index}, {max_index}].")
        _add_timing(timing, "dqn_replay_sample_seconds_window", time.perf_counter() - sample_started)

        build_started = time.perf_counter()
        observations = self._observations.index_select(0, indices_cpu).to(device=self.device)
        actions = self._actions.index_select(0, indices_cpu).to(device=self.device)
        rewards = self._rewards.index_select(0, indices_cpu).to(device=self.device)
        next_observations = self._next_observations.index_select(0, indices_cpu).to(device=self.device)
        dones = self._dones.index_select(0, indices_cpu).to(device=self.device)
        _add_timing(timing, "dqn_tensor_build_seconds_window", time.perf_counter() - build_started)

        if validate_tensors:
            validation_started = time.perf_counter()
            _validate_finite_tensor("dqn_replay_observations", observations)
            _validate_finite_tensor("dqn_replay_rewards", rewards)
            _validate_finite_tensor("dqn_replay_next_observations", next_observations)
            _add_timing(timing, "dqn_validation_seconds_window", time.perf_counter() - validation_started)

        return DQNReplayBatch(
            observations=observations,
            actions=actions,
            rewards=rewards,
            next_observations=next_observations,
            dones=dones,
        )

    def _compact_transition(self, transition: JointTransition) -> DQNReplayItem:
        observation = _tensor_1d(transition.observation, expected_dim=self.observation_dim, device=torch.device("cpu")).clone()
        next_observation = _tensor_1d(
            transition.next_observation,
            expected_dim=self.observation_dim,
            device=torch.device("cpu"),
        ).clone()
        action = _dqn_action_tensor(
            transition.dqn_action,
            action_count=self.action_count,
            device=torch.device("cpu"),
        ).clone()
        reward = _weighted_reward(
            global_reward=transition.reward_global,
            local_reward=transition.reward_dqn_local,
            explicit_reward=transition.reward_dqn_train,
            expected_reward=dqn_training_reward(
                reward_global=transition.reward_global,
                reward_dqn_local=transition.reward_dqn_local,
                reward_blend=self.reward_blend,
            ),
        )
        return DQNReplayItem(
            observation=observation,
            action=action,
            reward=reward,
            next_observation=next_observation,
            done=transition.bootstrap_done,
        )


def _validate_discount(name: str, value: float) -> None:
    _validate_finite_float(name, value)
    if not 0.0 <= value <= 1.0:
        raise ValueError(f"{name} must be within [0, 1].")


def ppo_training_reward(
    *,
    reward_global: float,
    reward_ppo_local: float,
    reward_blend: JointRewardBlendConfig | None = None,
) -> float:
    """Return PPO's role-specific training reward."""

    _validate_finite_float("reward_global", reward_global)
    _validate_finite_float("reward_ppo_local", reward_ppo_local)
    blend = reward_blend or JointRewardBlendConfig()
    return float((blend.ppo_global_weight * reward_global) + (blend.ppo_local_weight * reward_ppo_local))


def dqn_training_reward(
    *,
    reward_global: float,
    reward_dqn_local: float,
    reward_blend: JointRewardBlendConfig | None = None,
) -> float:
    """Return DQN's local-health-gated training reward."""

    _validate_finite_float("reward_global", reward_global)
    _validate_finite_float("reward_dqn_local", reward_dqn_local)
    blend = reward_blend or JointRewardBlendConfig()
    local_health = smoothstep((reward_dqn_local + blend.dqn_local_health_offset) / blend.dqn_local_health_scale)
    return float(
        (blend.dqn_local_weight * reward_dqn_local)
        + (blend.dqn_global_weight * local_health * reward_global)
    )


def smoothstep(value: float) -> float:
    """Smoothly map a scalar into [0, 1] using x^2 * (3 - 2x)."""

    _validate_finite_float("smoothstep_value", value)
    x = min(1.0, max(0.0, float(value)))
    return float((x * x) * (3.0 - (2.0 * x)))


def _weighted_reward(
    *,
    global_reward: float,
    local_reward: float,
    explicit_reward: float,
    expected_reward: float,
) -> float:
    _validate_finite_float("global_reward", global_reward)
    _validate_finite_float("local_reward", local_reward)
    _validate_finite_float("explicit_reward", explicit_reward)
    _validate_finite_float("expected_reward", expected_reward)
    if abs(float(explicit_reward) - expected_reward) > 1e-5:
        return float(expected_reward)
    return float(explicit_reward)


def _tensor_1d(value: Tensor, *, expected_dim: int, device: torch.device) -> Tensor:
    if value.ndim == 1:
        tensor = value.detach().to(device=device, dtype=torch.float32)
    elif value.ndim == 2 and value.shape[0] == 1:
        tensor = value.detach().to(device=device, dtype=torch.float32).squeeze(0)
    else:
        raise ValueError(f"expected tensor shape ({expected_dim},) or (1, {expected_dim}), got {tuple(value.shape)}.")
    if tensor.shape[0] != expected_dim:
        raise ValueError(f"expected tensor dimension {expected_dim}, got {tensor.shape[0]}.")
    _validate_finite_tensor("tensor", tensor)
    return tensor


def _scalar_tensor(value: Tensor | float, *, device: torch.device) -> Tensor:
    if isinstance(value, Tensor):
        if value.ndim == 0:
            tensor = value.detach().to(device=device, dtype=torch.float32)
        elif value.ndim == 1 and value.shape[0] == 1:
            tensor = value.detach().to(device=device, dtype=torch.float32).squeeze(0)
        else:
            raise ValueError(f"expected scalar tensor shape () or (1,), got {tuple(value.shape)}.")
        _validate_finite_tensor("scalar", tensor)
        return tensor
    _validate_finite_float("scalar", value)
    return torch.tensor(float(value), dtype=torch.float32, device=device)


def _dqn_action_tensor(value: Tensor, *, action_count: int, device: torch.device) -> Tensor:
    if value.ndim == 0:
        raw = value.detach()
    elif value.ndim == 1 and value.shape[0] == 1:
        raw = value.detach().squeeze(0)
    else:
        raise ValueError(f"expected discrete action tensor shape () or (1,), got {tuple(value.shape)}.")
    if raw.dtype not in (torch.uint8, torch.int8, torch.int16, torch.int32, torch.int64, torch.long):
        raise ValueError(f"discrete action tensor must use an integer dtype, got {raw.dtype}.")
    action = raw.to(device=device, dtype=torch.long)
    action_int = int(action.item())
    if not 0 <= action_int < action_count:
        raise ValueError(f"discrete action must be in [0, {action_count - 1}], got {action_int}.")
    return action


def _state_tensor(state: Mapping[str, Any], key: str, *, dtype: torch.dtype) -> Tensor:
    value = state.get(key)
    if not isinstance(value, Tensor):
        raise TypeError(f"DQN replay state field {key!r} must be a tensor.")
    return value.detach().to(device=torch.device("cpu"), dtype=dtype)


def _validate_finite_float(name: str, value: float) -> None:
    if not math.isfinite(float(value)):
        raise ValueError(f"{name} must be finite, got {value!r}.")


def _validate_finite_tensor(name: str, value: Tensor) -> None:
    if not torch.isfinite(value).all().item():
        raise ValueError(f"{name} contains non-finite values.")


def _add_timing(timing: MutableMapping[str, float] | None, key: str, elapsed: float) -> None:
    if timing is None:
        return
    timing[key] = float(timing.get(key, 0.0)) + max(0.0, float(elapsed))
